apiVersion: v1
kind: Pod
metadata:
  name: abcapp
  namespace: default
  labels:
     app: demo
spec:
  containers:
  - name: abccon
    image: adamumoh/abc_tech:latest
    ports:
      - containerPort: 8080
        protocol: TCP
---

apiVersion: v1
kind: Service
metadata:
  name: abcsvc
spec:
  type: NodePort
  selector:
   app: demo
  ports:
    - containerPort: 32000
      protocol: TCP
      targetport: 8080

