apiVersion: v1
kind: Pod
metadata:
  name: abcapp
  namespace: default
  labels:
     app: demo
spec:
  containers:
  - name: abccon
    image: adamumoh/abc_tech:latest
    ports:
    - 8080
---

apiVersion: v1
kind: Service
metadata:
  name: abcsvc
spec:
  type: NodePort
  selector:
   app: demo
  ports:
    protocol: TCP
    port: 32000
    targetport: 8080

